<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Comment extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Comment_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $comment = $this->Comment_model->get_all();

        $data = array(
            'comment_data' => $comment
        );

        $this->template->load('template','comment_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Comment_model->get_by_id($id);
        if ($row) {
            $data = array(
		'create_at' => $row->create_at,
		'id' => $row->id,
		'suryvey_id' => $row->suryvey_id,
		'text' => $row->text,
		'update_at' => $row->update_at,
	    );
            $this->template->load('template','comment_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('comment'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('comment/create_action'),
	    'create_at' => set_value('create_at'),
	    'id' => set_value('id'),
	    'suryvey_id' => set_value('suryvey_id'),
	    'text' => set_value('text'),
	    'update_at' => set_value('update_at'),
	);
        $this->template->load('template','comment_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
        		'create_at' => $this->input->post('create_at',TRUE),
        		'suryvey_id' => $this->input->post('suryvey_id',TRUE),
        		'text' => $this->input->post('text',TRUE),
        		'update_at' => $this->input->post('update_at',TRUE),
        	    );

            $this->Comment_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('comment'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Comment_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('comment/update_action'),
		'create_at' => set_value('create_at', $row->create_at),
		'id' => set_value('id', $row->id),
		'suryvey_id' => set_value('suryvey_id', $row->suryvey_id),
		'text' => set_value('text', $row->text),
		'update_at' => set_value('update_at', $row->update_at),
	    );
            $this->template->load('template','comment_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('comment'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'create_at' => $this->input->post('create_at',TRUE),
		'suryvey_id' => $this->input->post('suryvey_id',TRUE),
		'text' => $this->input->post('text',TRUE),
		'update_at' => $this->input->post('update_at',TRUE),
	    );

            $this->Comment_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('comment'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Comment_model->get_by_id($id);

        if ($row) {
            $this->Comment_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('comment'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('comment'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('create_at', 'create at', 'trim|required');
	$this->form_validation->set_rules('suryvey_id', 'suryvey id', 'trim|required');
	$this->form_validation->set_rules('text', 'text', 'trim|required');
	$this->form_validation->set_rules('update_at', 'update at', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Comment.php */
/* Location: ./application/controllers/Comment.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-24 01:50:59 */
/* http://harviacode.com */