<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class History extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('History_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $history = $this->History_model->get_all();

        $data = array(
            'history_data' => $history
        );

        $this->template->load('template','history/history_list', $data);
    }

    public function read($id) 
    {
        $row = $this->History_model->get_by_id($id);
        if ($row) {
            $data = array(
		'create_at' => $row->create_at,
		'id' => $row->id,
		'status' => $row->status,
		'text' => $row->text,
		'update_at' => $row->update_at,
	    );
            $this->template->load('template','history/history_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('history'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('history/create_action'),
	    'create_at' => set_value('create_at'),
	    'id' => set_value('id'),
	    'status' => set_value('status'),
	    'text' => set_value('text'),
	    'update_at' => set_value('update_at'),
	);
        $this->template->load('template','history/history_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'create_at' => $this->input->post('create_at',TRUE),
		'status' => $this->input->post('status',TRUE),
		'text' => $this->input->post('text',TRUE),
		'update_at' => $this->input->post('update_at',TRUE),
	    );

            $this->History_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('history'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->History_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('history/update_action'),
		'create_at' => set_value('create_at', $row->create_at),
		'id' => set_value('id', $row->id),
		'status' => set_value('status', $row->status),
		'text' => set_value('text', $row->text),
		'update_at' => set_value('update_at', $row->update_at),
	    );
            $this->template->load('template','history/history_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('history'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'create_at' => $this->input->post('create_at',TRUE),
		'status' => $this->input->post('status',TRUE),
		'text' => $this->input->post('text',TRUE),
		'update_at' => $this->input->post('update_at',TRUE),
	    );

            $this->History_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('history'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->History_model->get_by_id($id);

        if ($row) {
            $this->History_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('history'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('history'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('create_at', 'create at', 'trim|required');
	$this->form_validation->set_rules('status', 'status', 'trim|required');
	$this->form_validation->set_rules('text', 'text', 'trim|required');
	$this->form_validation->set_rules('update_at', 'update at', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file History.php */
/* Location: ./application/controllers/History.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-03 00:21:13 */
/* http://harviacode.com */