<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tire extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tire_model');
        $this->load->library('form_validation');
        if($this->session->userdata('user_logedin') != 'TRUE'){ redirect('index.php/login', 'refresh');}
    }

    public function index()
    {
        $tire = $this->Tire_model->get_all();

        $data = array(
            'tire_data' => $tire
        );

        $this->template->load('template','tire/tire_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Tire_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'name' => $row->name,
		'noseri' => $row->noseri,
		'stock' => $row->stock,
		'create_at' => $row->create_at,
		'update_at' => $row->update_at,
	    );
            $this->template->load('template','tire/tire_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url().'index.php/tire');
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('index.php/tire/create_action'),
	    'id' => set_value('id'),
	    'name' => set_value('name'),
	    'noseri' => set_value('noseri'),
	    'stock' => set_value('stock')
	);
        $this->template->load('template','tire/tire_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
		'noseri' => $this->input->post('noseri',TRUE),
		'stock' => $this->input->post('stock',TRUE),
    'create_at' => date('Y-m-d h:m:s')
	    );

            $this->Tire_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(base_url().'index.php/tire');
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tire_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('index.php/tire/update_action'),
		'id' => set_value('id', $row->id),
		'name' => set_value('name', $row->name),
		'noseri' => set_value('noseri', $row->noseri),
		'stock' => set_value('stock', $row->stock)
	    );
            $this->template->load('template','tire/tire_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url().'index.php/tire');
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
		'noseri' => $this->input->post('noseri',TRUE),
		'stock' => $this->input->post('stock',TRUE)
	    );

            $this->Tire_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(base_url().'index.php/tire');
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tire_model->get_by_id($id);

        if ($row) {
            $this->Tire_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(base_url().'index.php/tire');
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url().'index.php/tire');
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('name', 'name', 'trim|required');
	$this->form_validation->set_rules('noseri', 'noseri', 'trim|required');
	$this->form_validation->set_rules('stock', 'stock', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tire.php */
/* Location: ./application/controllers/Tire.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-21 03:31:19 */
/* http://harviacode.com */