<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Warehouse extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Warehouse_model');
        $this->load->library('form_validation');
        if($this->session->userdata('user_logedin') != 'TRUE'){ redirect('index.php/login', 'refresh');}
    }

    public function index()
    {
        $warehouse = $this->Warehouse_model->get_all();

        $data = array(
            'warehouse_data' => $warehouse
        );

        $this->template->load('template','warehouse/warehouse_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Warehouse_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'name' => $row->name,
		'alamat' => $row->alamat,
		'create_at' => $row->create_at,
		'update_at' => $row->update_at,
	    );
            $this->template->load('template','warehouse/warehouse_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('index.php/warehouse'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('index.php/warehouse/create_action'),
	    'id' => set_value('id'),
	    'name' => set_value('name'),
	    'alamat' => set_value('alamat'),
	);
        $this->template->load('template','warehouse/warehouse_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
		'alamat' => $this->input->post('alamat',TRUE),
		'create_at' => date('Y-m-d'),
	    );

            $this->Warehouse_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('index.php/warehouse'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Warehouse_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('index.php/warehouse/update_action'),
		'id' => set_value('id', $row->id),
		'name' => set_value('name', $row->name),
		'alamat' => set_value('alamat', $row->alamat),
	    );
            $this->template->load('template','warehouse/warehouse_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('index.php/warehouse'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
		'alamat' => $this->input->post('alamat',TRUE),
	    );

            $this->Warehouse_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('index.php/warehouse'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Warehouse_model->get_by_id($id);

        if ($row) {
            $this->Warehouse_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('index.php/warehouse'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('index.php/warehouse'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('name', 'name', 'trim|required');
	$this->form_validation->set_rules('alamat', 'alamat', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Warehouse.php */
/* Location: ./application/controllers/Warehouse.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-31 05:38:21 */
/* http://harviacode.com */