<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Warna extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model(array('Warna_model','User_model'));
        $this->load->library('form_validation');
        if($this->session->userdata('user_logedin') != 'TRUE'){ redirect('login', 'refresh');}
        if($this->session->userdata('user_level') != '1'){ redirect('login', 'refresh');}
    }

    public function index()
    {
        $warna = $this->Warna_model->get_all();

        $data = array(
            'warna_data' => $warna
        );
        $this->template->load('template','warna/warna_list', $data);
    }

    public function get_user(){
      $data = $this->User_model->get_all();
      echo json_encode($data);
    }

    public function read($id) 
    {
        $row = $this->Warna_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'name' => $row->name,
		'kode' => $row->kode,
		'username' => $row->username,
		'create_at' => $row->create_at,
	    );
            $this->template->load('template','warna/warna_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('warna'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('warna/create_action'),
	    'id' => set_value('id'),
	    'name' => set_value('name'),
	    'kode' => set_value('kode'),
	    'user_id' => set_value('user_id'),
	    // 'create_at' => set_value('create_at'),
	);
        $this->template->load('template','warna/warna_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
		'kode' => $this->input->post('kode',TRUE),
		'user_id' => $this->input->post('user_id',TRUE),
		// 'create_at' => $this->input->post('create_at',TRUE),
	    );

            $this->Warna_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('warna'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Warna_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('warna/update_action'),
		'id' => set_value('id', $row->id),
		'name' => set_value('name', $row->name),
		'kode' => set_value('kode', $row->kode),
		'user_id' => set_value('user_id', $row->user_id),
        'username' => set_value('username', $row->username),
		// 'create_at' => set_value('create_at', $row->create_at),
	    );
            $this->template->load('template','warna/warna_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('warna'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
		'kode' => $this->input->post('kode',TRUE),
		'user_id' => $this->input->post('user_id',TRUE),
		// 'create_at' => $this->input->post('create_at',TRUE),
	    );

            $this->Warna_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('warna'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Warna_model->get_by_id($id);

        if ($row) {
            $this->Warna_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('warna'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('warna'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('name', 'name', 'trim|required');
	$this->form_validation->set_rules('kode', 'kode', 'trim|required');
	$this->form_validation->set_rules('user_id', 'user id', 'trim|required');
	// $this->form_validation->set_rules('create_at', 'create at', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Warna.php */
/* Location: ./application/controllers/Warna.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-06 01:13:08 */
/* http://harviacode.com */