<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Check_model extends CI_Model
{

    public $table = 'check';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_id_complete($id)
    {
         $this->db->select  ("check.id,
                              check.kode,
                              check.examiner,
                              check.date_check,
                              check.create_at,
                              check.update_at,
                              delivery.create_at AS create_kode");
        $this->db->from('check');
        $this->db->join('delivery','check.kode=delivery.kode', 'LEFT');
        $this->db->where('check.id', $id);
        return $this->db->get()->row();
    }

    function get_detail($kode)
    {
        $this->db->select('*');
        $this->db->from('check_item');
        $this->db->where('check_item.kode', $kode);
        $this->db->where('check_item.status=1');
        return $this->db->get()->result();
    }

    function get_range($first,$last)
    {
        $this->db->select('check.id,
                    check.kode,
                    check.examiner,
                    check.date_check,
                    check.create_at,
                    check.update_at,
                    delivery.create_at AS create_kode,
                    MONTH(delivery.create_at) AS bulan, YEAR(delivery.create_at) AS tahun');
        $this->db->from('check');
        $this->db->join('delivery','check.kode=delivery.kode', 'LEFT');
        $this->db->where('check.create_at>=', $first);
        $this->db->where('check.create_at<=', $last);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get()->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('examiner', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('examiner', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    public function insert_batch($data){
      return $this->db->insert_batch('check_item', $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    public function update_batch($id,$data){
        $this->db->where($this->id, $id);
        $this->db->update('check_item', $data);  
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function deleteKode($id)
    {
        $this->db->where('kode', $id);
        $this->db->delete($this->table);
    }

    function deleteKodeDetail($id)
    {
        $this->db->where('kode', $id);
        $this->db->delete('check_item');
    }

}

/* End of file Check_model.php */
/* Location: ./application/models/Check_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-31 04:41:27 */
/* http://harviacode.com */