<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Comment_model extends CI_Model
{

    public $table = 'comment';
    public $id = 'id';
    public $order = 'DESC';
    public $tgl = 'create_at';

    function __construct()
    {
        parent::__construct();
    }

    function get_count($svno)
    {
      $this->db->where('sv_no', $svno);
      return $this->db->count_all_results($this->table);
    }

    function get_svno($svno)
    {
        $this->db->select('nama,category,text,foto,comment.create_at as tgl');
        $this->db->join('user', 'user.id=comment.user_id');
        $this->db->where('sv_no', $svno);
        $this->db->order_by('comment.create_at', $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('suryvey_id', $q);
	$this->db->or_like('text', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('suryvey_id', $q);
	$this->db->or_like('text', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Comment_model.php */
/* Location: ./application/models/Comment_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-24 01:50:59 */
/* http://harviacode.com */