<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class History_model extends CI_Model
{

    public $table = 'history';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_count($svno,$status)
    {
      if($status != NULL){
      $this->db->where('status', $status);
      }
      $this->db->where('sv_no', $svno);
      return $this->db->count_all_results($this->table);
    }

    function get_svno($svno)
    {
        // $this->db->where('sv_no', $svno);
        // $this->db->order_by($this->id, $this->order);
        // return $this->db->get($this->table)->result();

        $this->db->select('history.id as id,history.sv_no as sv_no,user.username as username,history.text as text,history.status as status,history.user_id as user_id,history.create_at as create_at,history.update_at as update_at');
        $this->db->join('user', 'user.id=history.user_id');
        $this->db->where('history.sv_no', $svno);
        return $this->db->get($this->table)->result();
    }

    function get_svno_history($svno,$status)
    {
        $this->db->where('sv_no', $svno);
        $this->db->where('status', $status);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('text', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('text', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file History_model.php */
/* Location: ./application/models/History_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-03 00:21:13 */
/* http://harviacode.com */