<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Item_model extends CI_Model
{

    public $table = 'item';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('item.id as id, item.name as name,item.category as category,unit.name as unit,create_at,update_at');
        $this->db->join('unit', 'unit.id=item.unit_id');
        $this->db->order_by('item.name', 'ASC');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('item.id as id, item.name as name,item.category as category, item.unit_id unit_id, unit.name as unit,create_at,update_at');
        $this->db->join('unit', 'unit.id=item.unit_id');
        $this->db->where('item.id', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('category', $q);
	$this->db->or_like('satuan_id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('category', $q);
	$this->db->or_like('satuan_id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Item_model.php */
/* Location: ./application/models/Item_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-19 01:31:22 */
/* http://harviacode.com */