<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pending_bike_model extends CI_Model
{

    public $table = 'pending_bike';
    public $id = 'bike_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, 'DESC');
        $this->db->where('status<>','sold');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    function get_all_waiting()
    {
        //$this->db->order_by($this->id, $this->order);
        $this->db->where('status','waiting');
        $this->db->order_by('bike_code','asc');
        $this->db->order_by('bike_color','asc');
        $this->db->order_by('bike_id','asc');
        return $this->db->get($this->table)->result();
    }

    function get_all_waiting_update($id)
    {
        
        return $this->db->query("
            SELECT p.bike_id,p.bike_code,p.bike_color,p.bike_no_rangka,p.bike_no_mesin,p.bike_year,
            p.bike_faktur,p.status,p.delete,p.source FROM
            (SELECT bike_id FROM delivery_detail WHERE kode='".$id."') d
            INNER JOIN pending_bike p ON d.bike_id=p.bike_id
            UNION
            SELECT * FROM pending_bike WHERE STATUS='waiting'
            ORDER BY bike_code,bike_color,FIELD(`status`,'waiting','booked'),bike_id ASC
          ;   
          ")->result();
        //return $this->db->get()->result();
    }

    function get_all_waiting_model(){
      $this->db->SELECT('bike_code,bike_color');
      $this->db->group_by('bike_code,bike_color');
      return $this->db->get($this->table)->result();
    }
   

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('bike_id', $q);
	$this->db->or_like('bike_code', $q);
	$this->db->or_like('bike_color', $q);
	$this->db->or_like('bike_no_rangka', $q);
	$this->db->or_like('bike_no_mesin', $q);
	$this->db->or_like('bike_year', $q);
	$this->db->or_like('bike_faktur', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('bike_id', $q);
	$this->db->or_like('bike_code', $q);
	$this->db->or_like('bike_color', $q);
	$this->db->or_like('bike_no_rangka', $q);
	$this->db->or_like('bike_no_mesin', $q);
	$this->db->or_like('bike_year', $q);
	$this->db->or_like('bike_faktur', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function insert_batch($data)
    {
       $res = $this->db->insert_batch('pending_bike',$data);
            if($res){
                return TRUE;
            }else{
                return FALSE;
            }
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    public function update_batch($data){
        $this->db->update_batch($this->table, $data, 'bike_id');
    }

    function change_bike_status($id,$status)
    {
        $this->db->query("
              UPDATE `pending_bike` p 
              INNER JOIN  (SELECT bike_id FROM delivery_detail WHERE bike_id<>'0' AND kode='".$id."') d
              ON d.bike_id=p.bike_id
              SET `status`='".$status."'
          ");
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pending_bike_model.php */
/* Location: ./application/models/Pending_bike_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-19 08:42:20 */
/* http://harviacode.com */