<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Receive_model extends CI_Model
{

    public $table = 'receive';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function exist_row_check($field,$data){
        $this->db->where($field,$data);
        $this->db->from($this->table);
        $query = $this->db->get();
        return $query->num_rows();
    }

    function get_detail_by_kode($kode)
    {
        $this->db->select('receive_item.id id, receive_item.kode kode, receive_item.qty_received qty_received, receive_item.keterangan keterangan, delivery_detail.name name, delivery_detail.qty qty, delivery_detail.category category, delivery_detail.unit unit, delivery_detail.price price');
        $this->db->from('receive_item');
        $this->db->join('delivery_detail','delivery_detail.id=receive_item.delivery_detail_id', 'INNER');
        $this->db->where('delivery_detail.kode', $kode);
        $this->db->order_by('delivery_detail.kode', $this->order);
        return $this->db->get()->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('receiver', $q);
	$this->db->or_like('pdi', $q);
	$this->db->or_like('pic', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    function get_range($first,$last)
    {
        $this->db->select('receive.id id, receive.kode kode, receive.receiver receiver, receive.pdi pdi, receive.pic pic, receive.create_at create_at, receive.update_at update_at, delivery.status status, delivery.wr_penerima_id wr_penerima_id');
        $this->db->from('receive');
        $this->db->join('delivery','receive.kode=delivery.kode', 'LEFT');
        $this->db->where('receive.create_at>=', $first);
        $this->db->where('receive.create_at<=', $last);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get()->result();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('receiver', $q);
	$this->db->or_like('pdi', $q);
	$this->db->or_like('pic', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    public function insert_batch($data){
      return $this->db->insert_batch('receive_item', $data);
    }

    public function update_batch($data){
      return $this->db->update_batch('receive_item', $data, 'delivery_detail_id');
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Receive_model.php */
/* Location: ./application/models/Receive_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-30 05:47:25 */
/* http://harviacode.com */