<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Road_money_model extends CI_Model
{

    public $table = 'road_money';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where('road_money.id', $id);
        return $this->db->get($this->table)->row();
    }

     function get_by_id_complete($id)
    {
         $this->db->select  ("road_money.id,
                            road_money.kode,
                            road_money.table_money,
                            road_money.pulse,
                            road_money.create_at,
                            road_money.update_at,
                            delivery.create_at AS create_kode");
        $this->db->from('road_money');
        $this->db->join('delivery','road_money.kode=delivery.kode', 'LEFT');
        $this->db->where('road_money.id', $id);
        return $this->db->get()->row();
    }

    function get_by_kode($id)
    {
        $this->db->where('road_money.kode', $id);
        return $this->db->get($this->table)->row();
    }

    function exist_row_check($field,$data){
        $this->db->where($field,$data);
        $this->db->from($this->table);
        $query = $this->db->get();
        return $query->num_rows();
    }

    function get_price($kode)
    {
        $this->db->select('SUM(price)as price');
        $this->db->from('road_money_detail');
        $this->db->where('kode', $kode);
        $query = $this->db->get();
        return $query->first_row('array');
    }

    function get_range($first,$last)
    {
        $this->db->select('road_money.id id, road_money.kode kode, road_money.table_money table_money, road_money.pulse pulse, road_money.create_at create_at, road_money.update_at update_at,delivery.create_at AS create_kode');
        $this->db->from('road_money');
        $this->db->join('delivery','road_money.kode=delivery.kode', 'LEFT');
        $this->db->where('road_money.create_at>=', $first);
        $this->db->where('road_money.create_at<=', $last);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get()->result();
    }

    function get_regencies_by_id($id=null)
    {
        $this->db->where('regencies.province_id', '51');
        $this->db->where('regencies.id', $id);
        $this->db->order_by('name', 'ASC');
        return $this->db->get('regencies')->result();
    }

    function get_roadmoney_detail_by_id($id)
    {
        $this->db->where('road_money_detail.kode', $id);
        $this->db->order_by('kode', 'ASC');
        return $this->db->get('road_money_detail')->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('table_money', $q);
	$this->db->or_like('pulse', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('table_money', $q);
	$this->db->or_like('pulse', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    public function insert_batch($data){
      return $this->db->insert_batch('road_money_detail', $data);
    }

    public function update_batch($data){
      return $this->db->update_batch('road_money_detail', $data, 'id');
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function deleteKode($id)
    {
        $this->db->where('kode', $id);
        $this->db->delete($this->table);
    }

    function deleteKodeDetail($id)
    {
        $this->db->where('kode', $id);
        $this->db->delete('road_money_detail');
    }
}

/* End of file Road_money_model.php */
/* Location: ./application/models/Road_money_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-28 01:52:21 */
/* http://harviacode.com */