<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tire_in_model extends CI_Model
{

    public $table = 'tire_in';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('tire_in.id id, tire_in.tire_id tire_id, tire_in.amount amount, tire_in.user_id user_id, tire_in.create_at create_at, tire.id ids_tire, tire.name tire_name, user.username user_name');
        $this->db->join('tire', 'tire.id=tire_in.tire_id');
        $this->db->join('user', 'user.id=tire_in.user_id');
        $this->db->order_by('tire.name', $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_range($first,$last)
    {
        $this->db->select('tire_in.id id, tire_in.tire_id tire_id, tire_in.amount amount, tire_in.user_id user_id, tire_in.create_at create_at, tire.id ids_tire, tire.name tire_name, user.username user_name');
        $this->db->from('tire_in');
        $this->db->join('tire', 'tire.id=tire_in.tire_id', 'LEFT');
        $this->db->join('user', 'user.id=tire_in.user_id', 'LEFT');
        $this->db->where('tire_in.create_at>=', $first);
        $this->db->where('tire_in.create_at<=', $last);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('tire_in.id id, tire_in.tire_id tire_id, tire_in.amount amount, tire_in.user_id user_id, tire_in.create_at create_at, tire.id ids_tire, tire.name tire_name, user.username user_name');
        $this->db->join('tire', 'tire.id=tire_in.tire_id');
        $this->db->join('user', 'user.id=tire_in.user_id');
        $this->db->order_by('tire.name', $this->order);
        $this->db->where('tire_in.id', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tire_id', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('create_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('tire_id', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('create_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tire_in_model.php */
/* Location: ./application/models/Tire_in_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-21 03:31:24 */
/* http://harviacode.com */