<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tire_out_model extends CI_Model
{

    public $table = 'tire_out';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('tire_out.id id, tire_out.tire_id tire_id, tire_out.amount amount, tire_out.driver_id driver_id, tire_out.nopol nopol, tire_out.user_id user_id, tire_out.km_before km_before, tire_out.km_after km_after, tire_out.keterangan keterangan, tire_out.create_at create_at, tire_out.update_at update_at, tire.id ids_tire, tire.name tire_name, driver.name driver_name, user.username username');
        $this->db->from('tire_out');
        $this->db->join('tire', 'tire.id=tire_out.tire_id', 'LEFT');
        $this->db->join('driver', 'driver.id=tire_out.driver_id', 'LEFT');
        $this->db->join('user', 'user.id=tire_out.user_id', 'LEFT');
        $this->db->order_by('tire_out.id', $this->order);
        return $this->db->get()->result();
    }

    function get_range($first,$last)
    {
        $this->db->select('tire_out.id id, tire_out.tire_id tire_id, tire_out.amount amount, tire_out.driver_id driver_id, tire_out.nopol nopol, tire_out.user_id user_id, tire_out.km_before km_before, tire_out.km_after km_after, tire_out.keterangan keterangan, tire_out.create_at create_at, tire_out.update_at update_at, tire.id ids_tire, tire.name tire_name, driver.name driver_name, user.username username');
        $this->db->from('tire_out');
        $this->db->join('tire', 'tire.id=tire_out.tire_id', 'LEFT');
        $this->db->join('driver', 'driver.id=tire_out.driver_id', 'LEFT');
        $this->db->join('user', 'user.id=tire_out.user_id', 'LEFT');
        $this->db->where('tire_out.create_at>=', $first);
        $this->db->where('tire_out.create_at<=', $last);
        $this->db->order_by('tire_out.id', $this->order);
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('tire_out.id id, tire_out.tire_id tire_id, tire_out.amount amount, tire_out.driver_id driver_id, tire_out.nopol nopol, tire_out.user_id user_id, tire_out.km_before km_before, tire_out.km_after km_after, tire_out.keterangan keterangan, tire_out.create_at create_at, tire_out.update_at update_at, tire.id ids_tire, tire.name tire_name, driver.name driver_name, user.username username');
        $this->db->from('tire_out');
        $this->db->join('tire', 'tire.id=tire_out.tire_id', 'LEFT');
        $this->db->join('driver', 'driver.id=tire_out.driver_id', 'LEFT');
        $this->db->join('user', 'user.id=tire_out.user_id', 'LEFT');
        $this->db->where('tire_out.id', $id);
        $this->db->order_by('tire_out.id', $this->order);
        return $this->db->get()->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tire_id', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('driver_id', $q);
	$this->db->or_like('nopol', $q);
	$this->db->or_like('km_before', $q);
	$this->db->or_like('km_after', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('tire_id', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('driver_id', $q);
	$this->db->or_like('nopol', $q);
	$this->db->or_like('km_before', $q);
	$this->db->or_like('km_after', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tire_out_model.php */
/* Location: ./application/models/Tire_out_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-21 03:31:29 */
/* http://harviacode.com */