<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Truck_model extends CI_Model
{

    public $table = 'truck';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function search_nopol($title)
    {
        $this->db->like('nopol', $title , 'both');
        $this->db->order_by('nopol', 'ASC');
        $this->db->limit(10);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('nopol', $q);
	$this->db->or_like('nosin', $q);
	$this->db->or_like('norangka', $q);
	$this->db->or_like('production_year', $q);
	$this->db->or_like('jto_samsat', $q);
	$this->db->or_like('kir', $q);
	$this->db->or_like('km', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('nopol', $q);
	$this->db->or_like('nosin', $q);
	$this->db->or_like('norangka', $q);
	$this->db->or_like('production_year', $q);
	$this->db->or_like('jto_samsat', $q);
	$this->db->or_like('kir', $q);
	$this->db->or_like('km', $q);
	$this->db->or_like('create_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Truck_model.php */
/* Location: ./application/models/Truck_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-21 03:31:10 */
/* http://harviacode.com */