<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Warna_model extends CI_Model
{

    public $table = 'warna';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('warna.id as id,warna.name name,user.username as username,warna.kode as kode,warna.user_id as user_id,warna.create_at as create_at');
        $this->db->join('user', 'user.id=warna.user_id');
        $this->db->order_by('warna.id', $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('warna.id as id,warna.name name,user.username as username,warna.kode as kode,warna.user_id as user_id,warna.create_at as create_at');
        $this->db->join('user', 'user.id=warna.user_id');
        $this->db->where('warna.id', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('create_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Warna_model.php */
/* Location: ./application/models/Warna_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-06 01:13:08 */
/* http://harviacode.com */